apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      database: openfmb
      sslmode: disable
      postgresVersion: 1200
      timescaledb: true
    isDefault: true
    editable: false
